### PR TITLE
Update to 1.20.4

### PR DESCRIPTION
**Pull request by sj-hub9796**

### CODE REVIEW

**Comment by KaiKikuchi** [comment]
Hey, thanks for the PR! I believe we need a new "fabric1.20.4" for this and keep the "fabric1.20" branch untouched, but I am not entirely sure if I can change that on this PR.

**Comment by sj-hub9796** [comment]
oh, sry for late.
Could you please create a new branch? I'll close this PR so i can open new PR.

**Comment by KaiKikuchi** [comment]
Hi, I already created a new branch 2 days ago https://github.com/KaiKikuchi/ServerRedirect/tree/fabric1.20.4

**Comment by sj-hub9796** [comment]
> Hi, I already created a new branch 2 days ago https://github.com/KaiKikuchi/ServerRedirect/tree/fabric1.20.4

i'm blind XD
thx man!

**Pull request closed without merging**
